### ISSUE TITLE
문서 형식 변경

### ISSUE THREAD

**Issue by gunhoflash** [gunhoflash/UOScafe2code#3]
카페의 수가 많아짐에 따라 문서를 다르게 구성해야 할 필요성이 생기고 있습니다. 다같이 적절한 방안을 생각해봅시다.

**Comment by r4k0nb4k0n** [comment]
# 문서 형식 변경 의견

### 문제점
* 카페 정보를 나열하는 순서가 정해져 있지 않다.
* 하나의 문서에 모든 정보를 집약하기 때문에 카페 정보를 구체적으로 쓰면 복잡해 보인다.

### Contributing Guideline

* `./README.md`
    + 대략적인 위치 파악이 가능한 거점들을 기준으로 분류.
        - 시립대 정문/후문/쪽문, 경희대 정문/후문, 청량리역, 회기역 등
    + `카페 이름(총점) - 한줄평` 형식으로 작성.
    + `[카페 이름](./data/카페_이름.md)` 식으로 링크 걸기.
* `./data/카페_이름.md`
    + `외부링크`, `한줄평`, `평가`, `근황` 소제목.
    + `한줄평`과 `평가` 작성은 최초 커미터의 자유이지만 레포 메인테이너인 @gunhoflash 가 직접 가본 후 변경할 수 있음.
    + `한줄평`은 카페에 대한 인상, 특이점, 장/단점을 단숨에 읽기 쉽도록 20-40자 내외로 작성한다. 
    + `평가`는 별점 방식으로 부여한다.
        - 최소 ☆☆☆☆☆ ~ 최대 ★★★★★
        - 규모, 콘센트, 무선인터넷, 분위기, 총평 순으로 작성한다.
        - 총평은 규모, 콘센트, 무선인터넷, 분위기 별점의 평균이고, 소수점 첫째 자리에서 반올림한다.
    + `외부링크`는 구글/네이버/카카오 등 해당 카페에 대한 정보가 있는 링크를 건다.
        - `[네이버](https://store.naver.com/restaurants/detail?id=1193044845&tab=main)`
    + 해당 카페 관련 변경/특이사항 발생 시 `근황`에 다음과 같이 작성.
        - 사항 발생 시간 / 사항 내용
        - `YYYY-MM-DD / 확장 모니터를 들여왔습니다.`

급하게 썼는데 나중에 PR도 넣겠습니다.

**Comment by gunhoflash** [comment]
data 디렉토리를 uos, khu, hoegi_station의 3개 하위 디렉토리로 나누고 uos는 다시 jeongmoon, hoomoon, jjokmoon의 3개 하위 디렉토리로 나누는건 어떨까요?

**Comment by r4k0nb4k0n** [comment]
디렉터리를 세분화하여 위치를 나타나게 해보겠습니다. 그러면 기존 카페 정보가 담긴 파일 이름에 써진 위치 정보는 삭제하도록 하겠습니다.
곧 PR 넣겠습니다.

2019년 6월 16일 (일) 15:03, GF <notifications@github.com>님이 작성:
